### ISSUE TITLE
Server not seeing exisiting saves

### ISSUE THREAD

**Issue by doublee313** [OxideMod/Oxide.TheForest#14]
When I use the latest version of this server manager, it doesn't see my existing save files and keeps saying "Will force game to new because GameSetup.IsSavedGameTrue LevelSerializer.CanResume False" in my log. Did the save files move when using this tool? Thanks. Also, thanks again for continuing this.

**Comment by lukespragg** [comment]
Yes, the save files are located under your server install location.

**Comment by lukespragg** [comment]
The saves are in an entirely different location with vanilla The Forest vs. with Oxide installed.

**Comment by doublee313** [comment]
Can you refer me to instructions? I'm not looking to bother you.

**Comment by doublee313** [comment]
I am new to Oxide. I have used and am part of many other server tools such as Ark Server Manager, Conan Server Manager, etc. Most allow us to specify a save folder but I don’t see it here.

I’m using Windows so it should store in: C:\Users\%username%\appdata\locallow\sks\ds\multiplayer

I have search everywhere for the save path when using Oxide.  I’m just copying over the latest Data from your files and I notice it needs my “server.cfg” in the root of where I’m launching it. Not sure if that helps. So I have: C:\Servers:\TheForest and it’s all under there. But no save files. I created a new server and can’t locate them.

Thank you,

**Comment by lukespragg** [comment]
Right, that's where it would store it without Oxide. The Oxide location is where your server is installed, then saves, then save number. It should have the save files there once it saves once.

**Comment by doublee313** [comment]
It creates the Oxide folder but no saves. It keeps saying new map each
restart...

**Comment by lukespragg** [comment]
It isn't under the oxide folder, it's under the saves folder. I have tested and verified that it does indeed make the save files, and they are used when the server is restarted. The default save interval for The Forest is 30 minutes, with a minimum of 15 minutes, so keep that in mind. Saving at a structure doesn't save the server, that only saves your individual player's state.

**Comment by doublee313** [comment]
I didn't wait 30 mins. Lol. I had auto save on 15. I'll try again. Thx. Do
you need documention help?
