### ISSUE TITLE
Latest release isn't working

### ISSUE THREAD

**Issue by doublee313** [OxideMod/Oxide.TheForest#17]
When I copy the files over and open my server, it doesn't launch. It sits on this NULL error (see screenshot). It was working fine prior and all is setup correctly. I just updated and used the normal game files and it works without the Oxide.
![oxidesm](https://user-images.githubusercontent.com/26212809/40269544-194b26b4-5b4e-11e8-89ef-c043212c4ddf.png)

**Comment by lukespragg** [comment]
Please check your logs for errors, as I can't reproduce that.

**Comment by doublee313** [comment]
I have attached the logs. The issue was on the 18th. I'm not sure what you needed so here they are. The Oxide logs didn't show any errors (loaded like normal).
[logs.zip](https://github.com/OxideMod/Oxide.TheForest/files/2019554/logs.zip)

**Comment by doublee313** [comment]
I fixed it by deleting the "oxide" folder and letting it recreate it.

**Comment by lukespragg** [comment]
The issue is from an empty name being set in Oxide's stored data for players, it will be fixed in the upcoming build.

**Comment by doublee313** [comment]
I pinned it down to this file...if I just delete it that fixes it...oxide.covalence.data

**Comment by doublee313** [comment]
Now I have another issue with the saves not loading. Could this be because they added: // Savepath
saveFolderPath  ??

**Comment by lukespragg** [comment]
The save path is the location of saveFolderPath if set, or saves/Slot# (we set this as the fallback.)

**Comment by doublee313** [comment]
I have been using saves under the server folder as previously set. I set the config to use the same folder (so i can use it when as n upd as ye drops while you patch the manager) and it works. Im not sure what its doing now do im leaving it up for 30 mins to see what it saves to :)

**Comment by lukespragg** [comment]
Make sure it's under saves/Slot#, not saves/Multiplayer/Slot#.

**Comment by doublee313** [comment]
Ahhh. Ok. So the SavePath wont work with Oxide in the config?

I have it: D:\Servers\TheForest\Saves (its creates multiplayers/slot#....)

Oxide did use the same. If its removed Multiplayer this will be an issue if we update the server and use it while waiting for your patch. It was working fine with adding my path above.

**Comment by lukespragg** [comment]
saveFolderPath works fine with it, I was saying that we change the default to be under saves/Slot# instead of AppData where The Forest normally stores them. The "Multiplayer" from the path was also removed with our last patch.

**Comment by doublee313** [comment]
Hmmmm. SavePath isnt working on mine. Would it be easier to chat? Im Doublee#0313 on Discord.

**Comment by doublee313** [comment]
Ok I confirmed the saveFolderPath isn't working. The format needs to be:

saveFolderPath C:\Servers\TheForest\Saves\

It works without Oxide, but when I use Oxide it uses the default.

**Comment by doublee313** [comment]
I'm testing the  -savefolderpath <path> in my launch script....

**Comment by lukespragg** [comment]
If you have your save under saves/Multiplayer/Slot#, then you'd need to set that to:

saveFolderPath C:\Servers\TheForest\Saves\Multiplayer

**Comment by doublee313** [comment]
I see. My only concern is if we use the vanilla and then we just need to adjust the launcher or config file to add "multiplayer" back in. Make sense?

**Comment by lukespragg** [comment]
Mmm, yeah I see what you mean; didn't think of that. I'll probably revert that change.

**Comment by doublee313** [comment]
Yeah otherwise we actually have to copy the Slot1 back to Multiplayer, then back to Saves/Slot1, etc. :) I'm just trying to avoid problems from others bothering you like me. Lol.

**Comment by doublee313** [comment]
Can you send me a screenshot of what your console looks like? Mine seems to be not formatting right on the screen....
![screenshot](https://user-images.githubusercontent.com/26212809/40271022-904502e6-5b65-11e8-80d1-fcff8c115af6.png)

**Comment by lukespragg** [comment]
Made a few changes: https://oxidemod.org/threads/release-build-changelog.18147/page-18#post-400909

**Comment by doublee313** [comment]
Thank you. It's working great now.
