### ISSUE TITLE
Add time to Dedicated Server Started

### ISSUE THREAD

**Issue by doublee313** [OxideMod/Oxide.TheForest#18]
Is it possible to add a timestamp to Dedicated Server Started in the console? Im doing alot of troubleshooting and its nice to have a time to see when it came up :)

**Comment by lukespragg** [comment]
The server uptime is shown in the server console in the top right of the status bar on the server console.

**Comment by doublee313** [comment]
I dont see the time on mine :(

**Comment by lukespragg** [comment]
Total uptime is shown on the 3rd line, right side of the status bar:
![image](https://user-images.githubusercontent.com/671337/40270714-18de03a6-5b60-11e8-9cf3-e51ccbe27556.png)

Timestamps can be shown via all Oxide messages by setting MinimalistMode to false in the oxide/oxide.config.json file while the server is offline.

**Comment by doublee313** [comment]
Ah thx that explains.
