### ISSUE TITLE
'OnPlayerConnected' event fail when player server console show 'Unnamed' name for player

### ISSUE THREAD

**Issue by netzulo** [OxideMod/Oxide.TheForest#5]
_need issue template_

---

## Description 

'OnPlayerConnected' event fail when player server console show 'Unnamed' name for player at release [2.0.3767](https://github.com/OxideMod/Oxide.TheForest/releases/tag/2.0.3767)

## Forum POST

[http://oxidemod.org/threads/failed-to-call-hook-onplayerconnected.27869/#post-376323](http://oxidemod.org/threads/failed-to-call-hook-onplayerconnected.27869/#post-376323)

## Propose

Mitigate error at  https://github.com/netzulo/Oxide.TheForest/commit/e82b357fd2c01c499b2649dae367a575f2eb02da , just a propose... maybe we must to investigate why sometimes same player got Unnamed each of get real name

**Comment by netzulo** [comment]
it's solved , @lukespragg ????? :O

**Comment by lukespragg** [comment]
No, the underlying issue is not resolved yet, but this particular one is.

**Comment by netzulo** [comment]
ill keep my eyes open then! ty @lukespragg
